### ISSUE TITLE
New use case?

### ISSUE THREAD

**Issue by ghost** [bsouthga/d3-exploder#1]
Hi,
can I use exploder for the following use case?
Say I have a map and want to explode the area underneath the mouse cursor to highlight it without removing it from the map. As I understand it, exploder moves the existing features. What I need would be to create a temporary copy of a selected feature in order to show it over or next to the map - without having a hole in the map.
Thanks,
Thomas

**Comment by bsouthga** [comment]
Sorry for taking so long to respond! This is indeed possible with d3-exploder!

[Here is a JSFiddle example](http://jsfiddle.net/9Lpcm56n/2/)

Basically, I create two layers of the states...

``` javascript
    // add states which will form the static map
    var states = g.append("g")
        .attr("id", "states")
        .selectAll("path")
        .data(state_features)
        .enter().append("path")
        .attr('id', function(d) { return "fips_" + d.id; })
        .attr("d", path);

    // add states we will explode! 
    var explode_states = g.append("g")
        .attr("id", "explode-states")
        .selectAll("path")
        .data(state_features)
        .enter().append("path")
        .attr('id', function(d) { return "fips_" + d.id; })
        .attr("d", path);    
```

And keep the `explode_states` invisible with some css...

``` css
#explode-states path {
    fill : rgba(0,0,0,0);
    stroke : rgba(0,0,0,0);
}

#explode-states:hover {
    cursor:pointer;
}

#explode-states path.highlighted-state {
    fill: red;
}
```

Then, whenever we click on a state, use d3-exploder to position it to the side...

``` javascript
    // Here is the magic!
    // This exploder will create a grid of the states
    // when called on a featurelist selection
    var exploder = d3.geo.exploder()
        // use the same projection as the map
        .projection(projection)
        // size the state to have an area of 150 pixels
        .size(function(d, i) { return 100; })
        // position the center of the state 3/4 of the width and 1/2 the height
        .position(function(d, i) {
            return [500, height/2];
        })    

    var highlighted_state = null;

    explode_states.on('click', function() {

        d3.selectAll('.highlighted-state')
            .transition()
            .duration(500)
            .attr("d", path)
            .attr("transform", "translate(0,0)")
            .each('end', function() {
                d3.select(this).classed('highlighted-state', false);
            })

        d3.select(this)
            .classed('highlighted-state', true)
            .transition()
            .duration(500)
            .call(exploder); 
    });
```

Try poking around the JSFiddle example to get a sense of what is going on!

**Comment by timelyportfolio** [comment]
very nice, thanks so much for sharing this.

**Comment by ghost** [comment]
Thanks.
Sounds a bit resource intensive however.
You Americans are always making maps with a handful of states, but we in Germany handle polygons of about 400 counties, 4,500 communities or 8,200 ZIP codes regularly. Haven't tried the ZIP codes in LeafletJS yet, but the communities are working well there.
I will test how D3 / exploder behave under that load...

**Comment by bsouthga** [comment]
yeah, unfortunately thousands of svg paths are going to be a pain regardless. maybe canvas is the answer?
