### ISSUE TITLE
Use attribute for scatterplot values

### ISSUE THREAD

**Issue by maning** [bsouthga/d3-exploder#2]
I'm trying to use your example to do a scatterplot based on polygon attributes.  Any tips on how to do this?  The attributes I have in topojson are `area` and `shape`.

**Comment by bsouthga** [comment]
could you share a small code example? happy to take a look

**Comment by maning** [comment]
@bsouthga Thank you very much.  Here's the code sample, mostly yours :)

https://bl.ocks.org/maning/bcd01fd5664f3672e47f6f1b4b1fe78d

I have two attributes in the sample.json topojson (shape and area).  Ideally, I want several views:
- original map
- grid sorted by size (like the random grid sample)
- grid sorted by shape (like the random grid sample)
- scatterplot shape and size

**Comment by bsouthga** [comment]
I poked around a bit and tweaked the code a bit: https://bl.ocks.org/bsouthga/ed16007621d865726edc9f9678a2b657

I centered and scaled the map using the following: 

``` javascript
      var feature_collection = topojson.feature(us, us.objects.sample2);
      var state_features = feature_collection.features;
      var feature_domain = [0, state_features.length-1];

      // Compute the bounds of a feature of interest, then derive scale & translate.
      var b = path.bounds(feature_collection),
          s = .95 / Math.max((b[1][0] - b[0][0]) / width, (b[1][1] - b[0][1]) / height),
          t = [(width - s * (b[1][0] + b[0][0])) / 2, (height - s * (b[1][1] + b[0][1])) / 2];


      // Update the projection to use computed scale & translate.
      projection
          .scale(s)
          .translate(t);
```

Which was taken from Mike Bostock himself here: http://stackoverflow.com/a/14691788/1718488

I also tweaked the scatter plot example to be this: 

``` javascript
      // --------------------------
      //
      // Scatter Plot
      //
      // --------------------------
      addButton('scatter', function(d, i) {


        // hide axis
        x_axis_g.transition().duration(500).style('opacity', 1);
        y_axis_g.transition().duration(500).style('opacity', 1);

        states.transition()
              .duration(500)
              .call(
                exploder.position(function(d, i) {
                  var scaled_area = xScale(d.properties.area);
                  var scaled_perimeter = yScale(d.properties.perimeter);
                  return [scaled_area, scaled_perimeter];
                })
              );

      });
```

Which plots the buildings by their area vs their size. I think this might be closer to what you are looking for -- the main thing is to just center and scale the map.

**Comment by bsouthga** [comment]
closing this issue for now, let me know if the above wasn't what you meant!
